---
- name: Install group packages
  hosts: app,db
  become: true
  tasks:
    - name: Install packages for each group
      ansible.builtin.package:
        name: "{{ packages }}"
        state: present
- name: Manage local users on all hosts
  hosts: all
  become: true
  tasks:
    - name: Ensure users are present or absent
      ansible.builtin.user:
        name: "{{ item.name }}"
        shell: "{{ item.shell }}"
        state: "{{ item.state }}"
      loop: "{{ users }}"
- name: Create directories and files
  hosts: all
  become: true
  tasks:
    - name: Manage directories and files
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: "{{ item.state }}"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode }}"
      loop: "{{ files }}"
